from p4utils.mininetlib.network_API import NetworkAPI

net = NetworkAPI()

net.setLogLevel('info')
net.setCompiler(p4rt=True)
net.execScript('python3 controller.py', reboot=True)
net.setLogLevel('info')
net.enableCli()

net.addP4RuntimeSwitch('s1')
net.addP4RuntimeSwitch('s2')
net.addP4RuntimeSwitch('s3')
net.addP4RuntimeSwitch('s4')
net.addP4RuntimeSwitch('s5')
net.addP4RuntimeSwitch('s6')
net.addP4RuntimeSwitch('s7')
net.addP4RuntimeSwitch('s8')
net.setP4SourceAll('controller.p4')

net.addHost('h1')
net.addHost('h2')
net.addHost('h3')
net.addHost('h4')
net.addHost('h5')
net.addHost('h6')
net.addHost('h7')
net.addHost('h8')
net.addHost('h9')
net.addHost('h10')
net.addHost('h11')
net.addHost('h12')
net.addHost('h13')
net.addHost('h14')
net.addHost('h15')
net.addHost('h16')
net.addHost('h17')
net.addHost('h18')

net.addLink('h1','s1')
net.addLink('h2','s1')
net.addLink('h3','s1')
net.addLink('h4','s2')
net.addLink('h5','s2')
net.addLink('h6','s2')
net.addLink('h7','s3')
net.addLink('h8','s3')
net.addLink('h9','s3')
net.addLink('h10','s4')
net.addLink('h11','s4')
net.addLink('h12','s4')
net.addLink('h13','s5')
net.addLink('h14','s5')
net.addLink('h15','s5')
net.addLink('h16','s6')
net.addLink('h17','s6')
net.addLink('h18','s6')
net.addLink('s1','s7')
net.addLink('s2','s7')
net.addLink('s3','s7')
net.addLink('s4','s8')
net.addLink('s5','s8')
net.addLink('s6','s8')
net.addLink('s7','s8')

net.l3()
net.disablePcapDumpAll()
net.disableLogAll()
net.enableCli()
net.startNetwork()